#!/usr/bin/env python
import sys, os

MOOSE_PYTHON_DIR = os.path.abspath(os.path.join(os.path.dirname(os.path.realpath(__file__)), '..', 'share', 'moose', 'python'))
if not os.path.isdir(MOOSE_PYTHON_DIR):
    print('Could not locate the moose python directory', file=sys.stderr)
    os.exit(1)

sys.path.append(MOOSE_PYTHON_DIR)

from TestHarness import TestHarness
TestHarness.buildAndRun(sys.argv, None, MOOSE_PYTHON_DIR)
